openapi: 3.0.1
info:
  title: Ballerina HTTP File Server
  description: 'A simple HTTP file server written using Ballerina.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:9090/files/v1
paths:
  /list:
    get:
      tags:
      - files
      summary: List all the files
      operationId: listFiles
      responses:
        200:
          description: 'A JSON array with names of files available.'
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File' 
  /file/{filename}:
    get:
      tags:
      - file
      summary: The specified file
      operationId: getFile
      parameters:
      - name: filename
        in: path
        description: 'The name of the file to be fetched.'
        required: true
        schema:
          type: string
      responses:
        200:
          description: The specified file
          content:
            application/octet-stream
components:
  schemas:
    File:
      required:
        - name
      type: object
      properties:
        name:
          type: string
    
